# 06. jqdatasdk

In [2]:
import pandas as pd
import numpy as np

In [9]:
df = pd.DataFrame(np.random.randint(5, size=(10, 2)), index = pd.date_range('1/1/2023', periods=10), columns=['A', 'B'])

# 将 B 列最近 2 个值相加并生成新列
df['C'] = df['B'].rolling(window=2).sum()
df['D'] = df['B'].rolling(window=5).sum()

# 将 B 列最近 2 个值求平均并生成新列
df['E'] = df['B'].rolling(window=2, min_periods=1).mean()
df['F'] = df['B'].rolling(window=5, min_periods=1).mean()
df

            A  B    C     D    E     F
2023-01-01  1  0  NaN   NaN  0.0  0.00
2023-01-02  1  3  3.0   NaN  1.5  1.50
2023-01-03  0  0  3.0   NaN  1.5  1.00
2023-01-04  1  0  0.0   NaN  0.0  0.75
2023-01-05  1  4  4.0   7.0  2.0  1.40
2023-01-06  4  3  7.0  10.0  3.5  2.00
2023-01-07  2  2  5.0   9.0  2.5  1.80
2023-01-08  1  0  2.0   9.0  1.0  1.80
2023-01-09  2  3  3.0  12.0  1.5  2.40
2023-01-10  2  1  4.0   9.0  2.0  1.80

In [14]:
import jqdatasdk as jq
jq.auth('username', 'password')

In [15]:
count = jq.get_query_count()
print('当日可调用数据总条数为: ', count['total'])
print('当日剩余调用数据条数为: ', count['spare'])

当日可调用数据总条数为:  1000000
当日剩余调用数据条数为:  999961

In [16]:
data = jq.get_price('000001.XSHE', start_date='2023-01-01', end_date='2023-04-01')
data

             open  close   high    low       volume         money
2023-01-03  12.89  13.44  13.52  12.74  224759667.0  2.971547e+09
2023-01-04  13.38  13.98  14.08  13.31  224304293.0  3.110729e+09
2023-01-05  14.06  14.14  14.39  14.03  170600995.0  2.417272e+09
2023-01-06  14.16  14.27  14.37  14.14  122488383.0  1.747915e+09
2023-01-09  14.40  14.45  14.53  14.17  108343322.0  1.561368e+09
2023-01-10  14.41  14.10  14.54  14.05  130035799.0  1.851094e+09
2023-01-11  14.11  14.32  14.43  14.05   85080620.0  1.217451e+09
2023-01-12  14.42  14.32  14.42  14.18   64094241.0  9.143677e+08
2023-01-13  14.32  14.59  14.59  14.20   97221412.0  1.407181e+09
2023-01-16  14.59  14.72  14.92  14.50  159805652.0  2.356400e+09
2023-01-17  14.77  14.61  14.82  14.42   95863990.0  1.396152e+09
2023-01-18  14.59  14.75  14.82  14.56   73594156.0  1.083363e+09
2023-01-19  14.77  14.73  14.89  14.52   65751707.0  9.637446e+08
2023-01-20  14.80  14.77  14.88  14.64   62342082.0  9.201448e+08
2023-01-30  15.23  14.79  15.37  14.54  140780826.0  2.096868e+09
2023-01-31  14.88  14.63  15.14  14.60  105561006.0  1.568639e+09
2023-02-01  14.67  14.35  14.72  14.16  169371373.0  2.426472e+09
2023-02-02  14.39  14.25  14.43  13.93  161635227.0  2.280745e+09
2023-02-03  14.11  13.98  14.20  13.82  127675610.0  1.782106e+09
2023-02-06  13.76  13.67  13.79  13.53  134971896.0  1.838429e+09
2023-02-07  13.73  13.87  13.98  13.70   89064835.0  1.235298e+09
2023-02-08  13.90  13.71  13.98  13.70   67392476.0  9.287089e+08
2023-02-09  13.68  13.79  13.96  13.63   85058483.0  1.174362e+09
2023-02-10  13.76  13.65  13.78  13.53   86793113.0  1.184283e+09
2023-02-13  13.61  13.49  13.61  13.28  184391970.0  2.473405e+09
2023-02-14  13.52  13.63  13.65  13.47   93211136.0  1.263892e+09
2023-02-15  13.62  13.34  13.63  13.30  128071119.0  1.713567e+09
2023-02-16  13.35  13.28  13.58  13.18  131029426.0  1.757431e+09
2023-02-17  13.31  13.11  13.39  13.11   94074331.0  1.246777e+09
2023-02-20  13.18  13.81  13.81  13.17  216776066.0  2.945970e+09
2023-02-21  13.73  13.76  13.86  13.59  101463238.0  1.393153e+09
2023-02-22  13.67  13.69  13.78  13.61   65449230.0  8.957425e+08
2023-02-23  13.67  13.72  13.98  13.65   84458270.0  1.165540e+09
2023-02-24  13.69  13.53  13.70  13.47   74777815.0  1.012653e+09
2023-02-27  13.42  13.36  13.55  13.35   63660634.0  8.548540e+08
2023-02-28  13.42  13.45  13.52  13.29   62275072.0  8.333160e+08
2023-03-01  13.47  13.83  13.85  13.41  125326609.0  1.719711e+09
2023-03-02  13.79  13.90  14.10  13.73  104063276.0  1.447566e+09
2023-03-03  14.01  13.95  14.03  13.80   70779227.0  9.855521e+08
2023-03-06  13.96  13.52  13.96  13.39  149130114.0  2.023955e+09
2023-03-07  13.52  13.36  13.76  13.33  131044075.0  1.773655e+09
2023-03-08  13.31  13.21  13.32  13.08  112362823.0  1.479839e+09
2023-03-09  13.22  12.89  13.26  12.82  177837095.0  2.305766e+09
2023-03-10  12.69  12.83  12.95  12.69   87788025.0  1.128558e+09
2023-03-13  12.81  12.74  12.97  12.69  102501945.0  1.309490e+09
2023-03-14  12.68  12.56  12.69  12.43  117707742.0  1.474124e+09
2023-03-15  12.74  12.74  12.87  12.63  100322985.0  1.278262e+09
2023-03-16  12.58  12.52  12.72  12.50   93913382.0  1.182054e+09
2023-03-17  12.68  12.45  12.73  12.35  159475217.0  2.000832e+09
2023-03-20  12.46  12.27  12.54  12.25  121778661.0  1.505894e+09
2023-03-21  12.35  12.40  12.48  12.20   86123125.0  1.060914e+09
2023-03-22  12.45  12.49  12.57  12.41   89805486.0  1.121081e+09
2023-03-23  12.40  12.59  12.59  12.33   82390618.0  1.029380e+09
2023-03-24  12.54  12.52  12.55  12.46   63666455.0  7.963195e+08
2023-03-27  12.50  12.30  12.51  12.16  103299639.0  1.266945e+09
2023-03-28  12.36  12.34  12.43  12.25   69028994.0  8.517979e+08
2023-03-29  12.43  12.23  12.44  12.20   61058983.0  7.506876e+08
2023-03-30  12.25  12.38  12.41  12.11   84463962.0  1.035423e+09
2023-03-31  12.39  12.23  12.47  12.21   88658284.0  1.092263e+09

In [21]:
q = jq.query(jq.valuation).filter(jq.valuation.code=='000001.XSHE')
df = jq.get_fundamentals(q, '2023-01-03')
df

,id,code,pe_ratio,turnover_ratio,pb_ratio,ps_ratio,pcf_ratio,capitalization,market_cap,circulating_cap,circulating_market_cap,day,pe_ratio_lyr
0,2194089,000001.XSHE,6.0926,1.1307,0.7518,1.4808,-3.2168,1.940592e+06,2672.1949,1940554.695,2672.1438,2023-01-03,7.3541

In [26]:
# pd.set_option('max_rows', None)
temp = jq.get_industries(date='2023-01-03')
temp
# temp[temp['name'].str.contains('计算机')]

           name start_date
L72       商务服务业 1996-08-29
L71         租赁业 1997-01-30
G53       铁路运输业 1998-05-11
G57       管道运输业 1996-11-04
G56       航空运输业 1997-11-05
..          ...        ...
G60         邮政业 2017-02-16
N76       水利管理业 2012-01-01
N77  生态保护和环境治理业 2012-10-26
N78     公共设施管理业 1992-08-07
E50  建筑装饰和其他建筑业 1997-05-22

[90 rows x 2 columns]

In [27]:
temp[temp['name'].str.contains('计算机')]

                 name start_date
C39  计算机、通信和其他电子设备制造业 1990-12-19

In [28]:
# 获取计算机行业版块股票
pool = jq.get_industry_stocks('C39', date='2023-01-03')
pool

['000016.XSHE',
 '000020.XSHE',
 '000021.XSHE',
 '000045.XSHE',
 '000050.XSHE',
 '000063.XSHE',
 '000066.XSHE',
 '000100.XSHE',
 '000413.XSHE',
 '000536.XSHE',
 '000547.XSHE',
 '000561.XSHE',
 '000586.XSHE',
 '000636.XSHE',
 '000670.XSHE',
 '000687.XSHE',
 '000725.XSHE',
 '000727.XSHE',
 '000733.XSHE',
 '000748.XSHE',
 '000801.XSHE',
 '000810.XSHE',
 '000823.XSHE',
 '000938.XSHE',
 '000970.XSHE',
 '000977.XSHE',
 '000988.XSHE',
 '001229.XSHE',
 '001270.XSHE',
 '001308.XSHE',
 '001309.XSHE',
 '001339.XSHE',
 '002017.XSHE',
 '002025.XSHE',
 '002036.XSHE',
 '002045.XSHE',
 '002049.XSHE',
 '002052.XSHE',
 '002055.XSHE',
 '002077.XSHE',
 '002079.XSHE',
 '002089.XSHE',
 '002104.XSHE',
 '002106.XSHE',
 '002119.XSHE',
 '002130.XSHE',
 '002134.XSHE',
 '002137.XSHE',
 '002138.XSHE',
 '002151.XSHE',
 '002156.XSHE',
 '002161.XSHE',
 '002179.XSHE',
 '002180.XSHE',
 '002185.XSHE',
 '002189.XSHE',
 '002194.XSHE',
 '002199.XSHE',
 '002214.XSHE',
 '002217.XSHE',
 '002222.XSHE',
 '002231.XSHE',
 '002236.XSHE',
 '002241.XSHE',
 '002273.XSHE',
 '002281.XSHE',
 '002288.XSHE',
 '002289.XSHE',
 '002296.XSHE',
 '002308.XSHE',
 '002313.XSHE',
 '002351.XSHE',
 '002362.XSHE',
 '002369.XSHE',
 '002376.XSHE',
 '002383.XSHE',
 '002384.XSHE',
 '002387.XSHE',
 '002388.XSHE',
 '002389.XSHE',
 '002396.XSHE',
 '002402.XSHE',
 '002413.XSHE',
 '002414.XSHE',
 '002415.XSHE',
 '002426.XSHE',
 '002429.XSHE',
 '002436.XSHE',
 '002446.XSHE',
 '002449.XSHE',
 '002456.XSHE',
 '002463.XSHE',
 '002465.XSHE',
 '002475.XSHE',
 '002484.XSHE',
 '002506.XSHE',
 '002512.XSHE',
 '002519.XSHE',
 '002528.XSHE',
 '002577.XSHE',
 '002579.XSHE',
 '002583.XSHE',
 '002587.XSHE',
 '002600.XSHE',
 '002618.XSHE',
 '002635.XSHE',
 '002636.XSHE',
 '002655.XSHE',
 '002660.XSHE',
 '002681.XSHE',
 '002729.XSHE',
 '002766.XSHE',
 '002782.XSHE',
 '002792.XSHE',
 '002796.XSHE',
 '002806.XSHE',
 '002813.XSHE',
 '002815.XSHE',
 '002829.XSHE',
 '002835.XSHE',
 '002841.XSHE',
 '002845.XSHE',
 '002848.XSHE',
 '002855.XSHE',
 '002859.XSHE',
 '002861.XSHE',
 '002866.XSHE',
 '002869.XSHE',
 '002876.XSHE',
 '002881.XSHE',
 '002885.XSHE',
 '002888.XSHE',
 '002897.XSHE',
 '002902.XSHE',
 '002906.XSHE',
 '002913.XSHE',
 '002916.XSHE',
 '002925.XSHE',
 '002935.XSHE',
 '002937.XSHE',
 '002938.XSHE',
 '002947.XSHE',
 '002952.XSHE',
 '002955.XSHE',
 '002960.XSHE',
 '002962.XSHE',
 '002972.XSHE',
 '002977.XSHE',
 '002981.XSHE',
 '002983.XSHE',
 '002992.XSHE',
 '002993.XSHE',
 '003015.XSHE',
 '003019.XSHE',
 '003026.XSHE',
 '003028.XSHE',
 '003031.XSHE',
 '003040.XSHE',
 '300028.XSHE',
 '300042.XSHE',
 '300045.XSHE',
 '300046.XSHE',
 '300053.XSHE',
 '300065.XSHE',
 '300076.XSHE',
 '300077.XSHE',
 '300078.XSHE',
 '300079.XSHE',
 '300088.XSHE',
 '300101.XSHE',
 '300102.XSHE',
 '300114.XSHE',
 '300115.XSHE',
 '300120.XSHE',
 '300127.XSHE',
 '300128.XSHE',
 '300134.XSHE',
 '300136.XSHE',
 '300139.XSHE',
 '300155.XSHE',
 '300162.XSHE',
 '300177.XSHE',
 '300205.XSHE',
 '300211.XSHE',
 '300213.XSHE',
 '300219.XSHE',
 '300220.XSHE',
 '300223.XSHE',
 '300227.XSHE',
 '300232.XSHE',
 '300241.XSHE',
 '300256.XSHE',
 '300270.XSHE',
 '300282.XSHE',
 '300296.XSHE',
 '300301.XSHE',
 '300303.XSHE',
 '300308.XSHE',
 '300319.XSHE',
 '300322.XSHE',
 '300323.XSHE',
 '300327.XSHE',
 '300331.XSHE',
 '300346.XSHE',
 '300351.XSHE',
 '300353.XSHE',
 '300367.XSHE',
 '300373.XSHE',
 '300389.XSHE',
 '300390.XSHE',
 '300393.XSHE',
 '300394.XSHE',
 '300397.XSHE',
 '300408.XSHE',
 '300414.XSHE',
 '300433.XSHE',
 '300449.XSHE',
 '300455.XSHE',
 '300456.XSHE',
 '300458.XSHE',
 '300460.XSHE',
 '300474.XSHE',
 '300476.XSHE',
 '300479.XSHE',
 '300502.XSHE',
 '300504.XSHE',
 '300514.XSHE',
 '300516.XSHE',
 '300531.XSHE',
 '300543.XSHE',
 '300546.XSHE',
 '300548.XSHE',
 '300555.XSHE',
 '300563.XSHE',
 '300565.XSHE',
 '300566.XSHE',
 '300570.XSHE',
 '300581.XSHE',
 '300582.XSHE',
 '300590.XSHE',
 '300602.XSHE',
 '300615.XSHE',
 '300620.XSHE',
 '300623.XSHE',
 '300627.XSHE',
 '300628.XSHE',
 '300629.XSHE',
 '300632.XSHE',
 '300638.XSHE',
 '300647.XSHE',
 '300656.XSHE',
 '300657.XSHE',
 '300661.XSHE',
 '300666.XSHE',
 '300672.XSHE',
 '300679.XSHE',
 '300686.XSHE',
 '300689.XSHE',
 '300691.XSHE',
 '300698.XSHE',
 '300701.XSHE',
 '300708.XSHE',
 '300709.XSHE',
 '300710.XSHE',
 '300711.XSHE',
 '300726.XSHE',
 '300735.XSHE',
 '300739.XSHE',
 '300743.XSHE',
 '300747.XSHE',
 '300752.XSHE',
 '300762.XSHE',
 '300782.XSHE',
 '300787.XSHE',
 '300790.XSHE',
 '300793.XSHE',
 '300802.XSHE',
 '300807.XSHE',
 '300811.XSHE',
 '300814.XSHE',
 '300822.XSHE',
 '300831.XSHE',
 '300835.XSHE',
 '300842.XSHE',
 '300843.XSHE',
 '300847.XSHE',
 '300852.XSHE',
 '300857.XSHE',
 '300866.XSHE',
 '300870.XSHE',
 '300884.XSHE',
 '300903.XSHE',
 '300909.XSHE',
 '300916.XSHE',
 '300936.XSHE',
 '300939.XSHE',
 '300940.XSHE',
 '300951.XSHE',
 '300956.XSHE',
 '300964.XSHE',
 '300965.XSHE',
 '300968.XSHE',
 '300976.XSHE',
 '300991.XSHE',
 '301002.XSHE',
 '301041.XSHE',
 '301042.XSHE',
 '301045.XSHE',
 '301050.XSHE',
 '301051.XSHE',
 '301067.XSHE',
 '301086.XSHE',
 '301106.XSHE',
 '301123.XSHE',
 '301132.XSHE',
 '301135.XSHE',
 '301150.XSHE',
 '301152.XSHE',
 '301165.XSHE',
 '301176.XSHE',
 '301180.XSHE',
 '301182.XSHE',
 '301183.XSHE',
 '301189.XSHE',
 '301191.XSHE',
 '301205.XSHE',
 '301217.XSHE',
 '301280.XSHE',
 '301282.XSHE',
 '301285.XSHE',
 '301308.XSHE',
 '301318.XSHE',
 '301319.XSHE',
 '301321.XSHE',
 '301326.XSHE',
 '301328.XSHE',
 '301330.XSHE',
 '301366.XSHE',
 '301379.XSHE',
 '301389.XSHE',
 '301391.XSHE',
 '600060.XSHG',
 '600074.XSHG',
 '600100.XSHG',
 '600118.XSHG',
 '600130.XSHG',
 '600151.XSHG',
 '600171.XSHG',
 '600183.XSHG',
 '600198.XSHG',
 '600203.XSHG',
 '600234.XSHG',
 '600237.XSHG',
 '600260.XSHG',
 '600271.XSHG',
 '600288.XSHG',
 '600330.XSHG',
 '600345.XSHG',
 '600353.XSHG',
 '600355.XSHG',
 '600360.XSHG',
 '600363.XSHG',
 '600401.XSHG',
 '600405.XSHG',
 '600435.XSHG',
 '600460.XSHG',
 '600485.XSHG',
 '600498.XSHG',
 '600525.XSHG',
 '600552.XSHG',
 '600562.XSHG',
 '600563.XSHG',
 '600584.XSHG',
 '600601.XSHG',
 '600666.XSHG',
 '600680.XSHG',
 '600703.XSHG',
 '600707.XSHG',
 '600734.XSHG',
 '600745.XSHG',
 '600764.XSHG',
 '600775.XSHG',
 '600776.XSHG',
 '600839.XSHG',
 '600870.XSHG',
 '600877.XSHG',
 '600888.XSHG',
 '600898.XSHG',
 '600980.XSHG',
 '600990.XSHG',
 '601138.XSHG',
 '601231.XSHG',
 '601869.XSHG',
 '603002.XSHG',
 '603005.XSHG',
 '603019.XSHG',
 '603023.XSHG',
 '603025.XSHG',
 '603042.XSHG',
 '603052.XSHG',
 '603068.XSHG',
 '603083.XSHG',
 '603106.XSHG',
 '603115.XSHG',
 '603118.XSHG',
 '603133.XSHG',
 '603160.XSHG',
 '603186.XSHG',
 '603228.XSHG',
 '603236.XSHG',
 '603267.XSHG',
 '603290.XSHG',
 '603327.XSHG',
 '603328.XSHG',
 '603380.XSHG',
 '603386.XSHG',
 '603390.XSHG',
 '603496.XSHG',
 '603501.XSHG',
 '603516.XSHG',
 '603528.XSHG',
 '603595.XSHG',
 '603633.XSHG',
 '603660.XSHG',
 '603678.XSHG',
 '603712.XSHG',
 '603738.XSHG',
 '603773.XSHG',
 '603803.XSHG',
 '603890.XSHG',
 '603893.XSHG',
 '603920.XSHG',
 '603933.XSHG',
 '603936.XSHG',
 '603986.XSHG',
 '603989.XSHG',
 '603996.XSHG',
 '605058.XSHG',
 '605111.XSHG',
 '605118.XSHG',
 '605218.XSHG',
 '605258.XSHG',
 '605358.XSHG',
 '605588.XSHG',
 '688002.XSHG',
 '688007.XSHG',
 '688008.XSHG',
 '688011.XSHG',
 '688019.XSHG',
 '688020.XSHG',
 '688025.XSHG',
 '688027.XSHG',
 '688035.XSHG',
 '688036.XSHG',
 '688041.XSHG',
 '688047.XSHG',
 '688048.XSHG',
 '688049.XSHG',
 '688055.XSHG',
 '688061.XSHG',
 '688079.XSHG',
 '688080.XSHG',
 '688081.XSHG',
 '688086.XSHG',
 '688093.XSHG',
 '688100.XSHG',
 '688103.XSHG',
 '688107.XSHG',
 '688110.XSHG',
 '688123.XSHG',
 '688126.XSHG',
 '688132.XSHG',
 '688135.XSHG',
 '688138.XSHG',
 '688141.XSHG',
 '688143.XSHG',
 '688150.XSHG',
 '688153.XSHG',
 '688159.XSHG',
 '688167.XSHG',
 '688172.XSHG',
 '688175.XSHG',
 '688181.XSHG',
 '688182.XSHG',
 '688183.XSHG',
 '688184.XSHG',
 '688195.XSHG',
 '688205.XSHG',
 '688208.XSHG',
 '688209.XSHG',
 '688210.XSHG',
 '688213.XSHG',
 '688216.XSHG',
 '688220.XSHG',
 '688230.XSHG',
 '688234.XSHG',
 '688260.XSHG',
 '688261.XSHG',
 '688270.XSHG',
 '688272.XSHG',
 '688282.XSHG',
 '688286.XSHG',
 '688288.XSHG',
 '688311.XSHG',
 '688313.XSHG',
 '688322.XSHG',
 '688326.XSHG',
 '688332.XSHG',
 '688362.XSHG',
 '688371.XSHG',
 '688372.XSHG',
 '688375.XSHG',
 '688380.XSHG',
 '688381.XSHG',
 '688385.XSHG',
 '688387.XSHG',
 '688388.XSHG',
 '688396.XSHG',
 '688401.XSHG',
 '688403.XSHG',
 '688416.XSHG',
 '688418.XSHG',
 '688432.XSHG',
 '688439.XSHG',
 '688475.XSHG',
 '688489.XSHG',
 '688496.XSHG',
 '688498.XSHG',
 '688503.XSHG',
 '688511.XSHG',
 '688519.XSHG',
 '688525.XSHG',
 '688533.XSHG',
 '688538.XSHG',
 '688595.XSHG',
 '688601.XSHG',
 '688608.XSHG',
 '688609.XSHG',
 '688618.XSHG',
 '688636.XSHG',
 '688655.XSHG',
 '688661.XSHG',
 '688662.XSHG',
 '688665.XSHG',
 '688667.XSHG',
 '688668.XSHG',
 '688683.XSHG',
 '688689.XSHG',
 '688696.XSHG',
 '688711.XSHG',
 '688728.XSHG',
 '688766.XSHG',
 '688776.XSHG',
 '688788.XSHG',
 '688798.XSHG',
 '688800.XSHG',
 '688981.XSHG',
 '689009.XSHG']

In [29]:
len(pool)

558

In [49]:
import yfinance as yf

In [51]:
tickers = ['AAPL', 'BABA', 'BIDU', 'GOOGL', 'FB', 'AMZN']
data = yf.download(tickers = tickers, start = '2022-01-01', end='2022-12-31')
data

[*********************100%%**********************]  6 of 6 completed

1 Failed download:
['FB']: Exception('%ticker%: No timezone found, symbol may be delisted')

             Adj Close                                                      \
                  AAPL        AMZN        BABA        BIDU  FB       GOOGL
Date
2022-01-03  179.953888  170.404495  120.379997  149.100006 NaN  144.991501
2022-01-04  177.669968  167.522003  119.559998  146.529999 NaN  144.399506
2022-01-05  172.943985  164.356995  121.160004  143.880005 NaN  137.774994
2022-01-06  170.056961  163.253998  126.629997  150.750000 NaN  137.747498
2022-01-07  170.225067  162.554001  129.809998  153.330002 NaN  137.016998
...                ...         ...         ...         ...  ..         ...
2022-12-23  131.127060   85.250000   85.650002  111.610001 NaN   89.230003
2022-12-27  129.307236   83.040001   89.860001  116.480003 NaN   87.389999
2022-12-28  125.339409   81.820000   87.199997  111.599998 NaN   86.019997
2022-12-29  128.889572   84.180000   89.129997  115.099998 NaN   88.449997
2022-12-30  129.207779   84.000000   88.089996  114.379997 NaN   88.230003

                 Close                                      ...        Open  \
                  AAPL        AMZN        BABA        BIDU  ...        BABA
Date                                                        ...
2022-01-03  182.009995  170.404495  120.379997  149.100006  ...  119.379997
2022-01-04  179.699997  167.522003  119.559998  146.529999  ...  119.529999
2022-01-05  174.919998  164.356995  121.160004  143.880005  ...  118.000000
2022-01-06  172.000000  163.253998  126.629997  150.750000  ...  124.260002
2022-01-07  172.169998  162.554001  129.809998  153.330002  ...  130.240005
...                ...         ...         ...         ...  ...         ...
2022-12-23  131.860001   85.250000   85.650002  111.610001  ...   87.849998
2022-12-27  130.029999   83.040001   89.860001  116.480003  ...   86.550003
2022-12-28  126.040001   81.820000   87.199997  111.599998  ...   88.980003
2022-12-29  129.610001   84.180000   89.129997  115.099998  ...   87.625000
2022-12-30  129.929993   84.000000   88.089996  114.379997  ...   87.449997

                                           Volume                      \
                  BIDU  FB       GOOGL       AAPL      AMZN      BABA
Date
2022-01-03  148.910004 NaN  145.054993  104487900  63520000  16775300
2022-01-04  148.139999 NaN  145.395996   99310400  70726000  20824000
2022-01-05  143.820007 NaN  144.419998   94537600  64302000  36651100
2022-01-06  146.199997 NaN  136.998505   96904000  51958000  32045800
2022-01-07  152.979996 NaN  138.145493   86709100  46606000  38113000
...                ...  ..         ...        ...       ...       ...
2022-12-23  113.879997 NaN   87.110001   63814900  57433700  17949300
2022-12-27  113.099998 NaN   88.800003   69007800  57284000  22959900
2022-12-28  114.089996 NaN   86.980003   85438400  58228600  16268800
2022-12-29  112.809998 NaN   86.620003   75703700  54995900  12535400
2022-12-30  113.489998 NaN   86.980003   77034200  62401200  11926700


               BIDU  FB     GOOGL
Date
2022-01-03  2329000 NaN  28646000
2022-01-04  2876800 NaN  28400000
2022-01-05  3505900 NaN  54618000
2022-01-06  3839000 NaN  37348000
2022-01-07  2752000 NaN  29760000
...             ...  ..       ...
2022-12-23  1221600 NaN  23003000
2022-12-27  2668300 NaN  20097300
2022-12-28  1983800 NaN  19523200
2022-12-29  1454600 NaN  23333500
2022-12-30  1727600 NaN  23986300

[251 rows x 36 columns]